<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EREV332-PC" name="TestListenerExample" tests="8" failures="3" timestamp="5 Mar 2015 10:40:54 GMT" time="0.046" errors="0">
  <testcase name="t1" time="0.011" classname="com.nostalgiaguy.testng.test.ReporterListenerExample"/>
  <testcase name="t2" time="0.001" classname="com.nostalgiaguy.testng.test.ReporterListenerExample">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.RuntimeException but got org.testng.TestException: 
Method ReporterListenerExample.t2()[pri:0, instance:com.nostalgiaguy.testng.test.ReporterListenerExample@68f8fae4] should have thrown an exception of class java.lang.RuntimeException">
      <![CDATA[org.testng.TestException: 
Method ReporterListenerExample.t2()[pri:0, instance:com.nostalgiaguy.testng.test.ReporterListenerExample@68f8fae4] should have thrown an exception of class java.lang.RuntimeException
Method ReporterListenerExample.t2()[pri:0, instance:com.nostalgiaguy.testng.test.ReporterListenerExample@68f8fae4] should have thrown an exception of class java.lang.RuntimeException
	... 16 more
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- t2 -->
  <testcase name="t3" time="0.001" classname="com.nostalgiaguy.testng.test.ReporterListenerExample"/>
  <testcase name="t4" time="0.003" classname="com.nostalgiaguy.testng.test.ReporterListenerExample">
    <failure type="java.lang.AssertionError" message="expected [10] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [1]
	at com.nostalgiaguy.testng.test.ReporterListenerExample.t4(ReporterListenerExample.java:27)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- t4 -->
  <testcase name="t4" time="0.001" classname="com.nostalgiaguy.testng.test.ReporterListenerExample"/>
  <testcase name="t4" time="0.001" classname="com.nostalgiaguy.testng.test.ReporterListenerExample">
    <failure type="java.lang.AssertionError" message="expected [10] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [3]
	at com.nostalgiaguy.testng.test.ReporterListenerExample.t4(ReporterListenerExample.java:27)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- t4 -->
  <testcase name="t4" time="0.0" classname="com.nostalgiaguy.testng.test.ReporterListenerExample"/>
  <testcase name="t4" time="0.001" classname="com.nostalgiaguy.testng.test.ReporterListenerExample"/>
</testsuite> <!-- TestListenerExample -->
